name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test de formatos
      id: test-de-formatos
      uses: education/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 1
        setup-command: pip install pytest && pytest test.py
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        TEST-DE-FORMATOS_RESULTS: "${{steps.test-de-formatos.outputs.result}}"
      with:
        runners: test-de-formatos
